name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [ "bug", "triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Submit a report and help us improve our free and open-source Netdata Agent.

        :exclamation: Before submitting:
          - Verify that your issue is not already reported on GitHub.
          - Test if the latest release and master branch are affected too.
  - type: input
    id: netdata-component
    attributes:
      label: Component name
      description: |
        Let us know which component is affected by the bug. Our code is structured according to its component,
        so the component name is the same as the top level directory of the repository.
      placeholder: ex. web, packaging, collectors
    validations:
      required: true
  - type: textarea
    id: report-summary
    attributes:
      label: Bug report summary
      description: "Provide a clear and concise description of the bug you're experiencing."
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System info
      description: |
        Provide information about your system.
        To get this information, execute one of the following commands based on your OS:
        ```shell
        # Linux
        uname -a; grep -HvE "^#|URL" /etc/*release
        # BSD
        uname -a; uname -K
        # macOS
        uname -a; sw_vers
        ```
        **This will be automatically formatted into code, so no need for backticks.**
      render: shell
    validations:
      required: true
  - type: textarea
    id: netdata-buildfinfo
    attributes:
      label: Netdata build info
      description: |
        Provide output of `netdata -W buildinfo`
        (or `netdata -v` if you're using an old version of Netdata Agent, that doesn't support buildinfo).

        <details>
        <summary>If netdata not in PATH (netdata: command not found)</summary>

        If `netdata` process is running, use `ps` to find an absolute path to the `netdata` binary.

        ```shell
        $ ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata "
        /opt/netdata/usr/sbin/netdata
        ```

        </details>

        **This will be automatically formatted into code, so no need for backticks.**
      render: shell
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      description: |
        Tell us which 
        [installation method](https://learn.netdata.cloud/docs/agent/packaging/installer#alternative-methods) you used.
      multiple: true
      options:
        - "kickstart.sh"
        - "kickstart-static64.sh"
        - "native binary packages (.deb/.rpm)"
        - "from git"
        - "from source"
        - "docker"
        - "helmchart (kubernetes)"
        - "other"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Include gist of relevant config, logs, etc.
    validations:
      required: false
