name: "Feature request: Netdata Agent"
description: "Submit a feature request and help us improve our free and open-source Netdata Agent"
title: "[Feat]: "
labels: ["feature request", "needs triage"]
body:
  - type: markdown
    attributes:
      value: "### Thank you for contributing to our project!"
  - type: markdown
    attributes:
      value: |
        Submit a feature request and help us improve our free and open-source Netdata Agent.
  - type: textarea
    id: request-description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature you want or need.
    validations:
      required: true
  - type: dropdown
    id: request-priority
    attributes:
      label: Priority
      description: Priority.
      options:
        - "Nice to Have"
        - "Really Want"
        - "Blocker"
    validations:
      required: true
  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: Use cases.
    validations:
      required: true
  - type: textarea
    id: proposed-implementation
    attributes:
      label: Proposed implementation
      description: Proposed implementation.
    validations:
      required: false
